// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum DeviceType
{
	Phone(new String[][] { new String[] { "en_US", "Phone" }, new String[] { "nl_NL", "Phone" } }),
	Tablet(new String[][] { new String[] { "en_US", "Tablet" }, new String[] { "nl_NL", "Tablet" } }),
	Desktop(new String[][] { new String[] { "en_US", "Desktop" }, new String[] { "nl_NL", "Desktop" } });

	private java.util.Map<String,String> captions;

	private DeviceType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
