// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum EventStatus
{
	Running(new String[][] { new String[] { "en_US", "Running" }, new String[] { "nl_NL", "Bezig" } }),
	Completed(new String[][] { new String[] { "en_US", "Completed" }, new String[] { "nl_NL", "Voltooid" } }),
	Error(new String[][] { new String[] { "en_US", "Error" }, new String[] { "nl_NL", "Fout" } });

	private java.util.Map<String,String> captions;

	private EventStatus(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
